### ISSUE TITLE
Suggestion for more libraries

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [wasabeef/awesome-android-ui#1]
Not an issue, but may I offer my own repositories?
Here they are:
https://github.com/AndroidDeveloperLB?tab=repositories

Also, here are 2 apps that show libraries sample from within Android:
https://play.google.com/store/apps/details?id=com.desarrollodroide.repos
https://play.google.com/store/apps/details?id=com.inappsquared.devappsdirect﻿

**Comment by wasabeef** [comment]
Let me make a reference.

**Comment by bmelnychuk** [comment]
Can I suggest you 2 more
https://github.com/bmelnychuk/AndroidTreeView
https://github.com/bmelnychuk/WearCircleMenu

Thanks

**Comment by championswimmer** [comment]
Let me suggest another of mine 
https://github.com/championswimmer/Android-SocialButtons 
There are images in the README itself.
