### ISSUE TITLE
Add SmoothRefreshLayout

### ISSUE THREAD

**Issue by dkzwm** [wasabeef/awesome-android-ui#199]
A highly efficient refresh library for Android
[SmoothRefreshLayout](https://github.com/dkzwm/SmoothRefreshLayout)

**Comment by lhyocean** [comment]
缺少依赖了

**Comment by dkzwm** [comment]
@lhyocean 缺少依赖？ 本库只依赖Recyclerview和V4包.这一般都会依赖吧
