### ISSUE TITLE
[DEPRECATED] library Snackbar should be removed

### ISSUE THREAD

**Issue by hoseinit** [wasabeef/awesome-android-ui#217]
Hello,
Why a deprecated library like Snackbar is still in the list?
Shouldn't it be removed?

**Comment by Erdemtsynduev** [comment]
Hello, 
I completely agree, it's written in their repository - deprecated.

**Comment by hoseinit** [comment]
Shall I make a Pull request ?

**Comment by Erdemtsynduev** [comment]
I think yes

**Comment by hoseinit** [comment]
#218 Done!

**Comment by hoseinit** [comment]
#219 Done
