### ISSUE TITLE
Size problem

### ISSUE THREAD

**Issue by ppamorim** [wasabeef/awesome-android-ui#31]
Hi everyone!
I've notice a problem with the size of this repository. I need a long time to clone the project and I think:
Why the art directory is at master branch? We can create a branch only for pictures(gif) and reduce the size of the master branch.

**Comment by luna3504** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

luna3504@naver.com 님께 보내신 메일 <[awesome-android-ui] Size problem (#31)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
