### ISSUE TITLE
a large amount if list of the gif is not show successful, is it because the resource invalid?or should i change my setting? please help.

### ISSUE THREAD

**Issue by wuyuansu** [wasabeef/awesome-android-ui#318]

**Comment by zz3100201** [comment]
您的邮件我已收到。

**Comment by 416542923** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JackyKeke** [comment]
感谢你的来信，我会及时处理。祝工作顺利，万事如意

**Comment by wuyuansu** [comment]
thank you for replay. I already solved this problem. just add a IP mapping in etc file is fine. I should be more patient before ask for help. anyway, thank you for your excellent work as I benefit a lot from this awesome-android-ui. good luck.
