### ISSUE TITLE
AndroidTreeView repo is Duplicated

### ISSUE THREAD

**Issue by dhkfcm000** [wasabeef/awesome-android-ui#32]
This repo is listed twice. isn't it?

**Comment by luna3504** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

luna3504@naver.com 님께 보내신 메일 <[awesome-android-ui] AndroidTreeView repo is Duplicated (#32)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by wasabeef** [comment]
@dhkfcm000 oops... thank you.

fix : https://github.com/wasabeef/awesome-android-ui/commit/c4223ecbfd86df7038b066b4e97f03fa53bbe0d4
