### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mitogh** [wasabeef/awesome-android-ui#5]
I think should be better to have each section in a different document to load faster and to be more organized. For example:

```
|-- Readme.md (Index)
    |-- Material.md (Material)
    |-- Layout.md (Layout)
    ...
```

and so on. 

PD: Thanks for sharing this amazing resources.

**Comment by wasabeef** [comment]
Thanks. how about this, sir?

https://github.com/wasabeef/awesome-android-ui/tree/preview

**Comment by mitogh** [comment]
Yes, But I was saying in different files to load only the appropriate files for each section and not all for all the document.

Thanks for your reply :+1:

**Comment by wasabeef** [comment]
hey.

It's I want to display all of the items in the README.
hat should I do...

**Comment by mitogh** [comment]
Oh great, I understand, thanks for the reply, and again awesome work ;) :smile:

**Comment by ypresto** [comment]
Very long loading time and scroll position is not kept on each image is loaded. It has become usability problem. >_<

**Comment by wasabeef** [comment]
@ypresto 

i want your ideas. > w <

**Comment by marianpavel** [comment]
No quite, I usually load all the content in 8-10 seconds ...
