### ISSUE TITLE
How to use in android projects

### ISSUE THREAD

**Issue by dharmendrajadon** [wasabeef/awesome-android-ui#65]
What is needed to use this library?

**Comment by SArsalanK** [comment]
A code to integrate into. That's it.

**Comment by petebru** [comment]
very cool...  thankyou

**Comment by dharmendrajadon** [comment]
Can you please describe it?

**Comment by Ziv-Android** [comment]
Thank you very much…

**Comment by DanielMartinus** [comment]
@dharmendrajadon This is just a curated list. If you want to integrate anything from this list in your project. Navigate to the projects repository by clicking on the library name in de list. One of the requirements is mostly having a gradle compatible project. Then on the repository you mostly find a gradle line such as com.my.packagename:libraryname:1.0.0

**Comment by dharmendrajadon** [comment]
I got it. Thank You @DanielMartinus

**Comment by huangdandan6627** [comment]
不知道
