### ISSUE TITLE
Add new Elastic Progress Bar

### ISSUE THREAD

**Issue by michelelacorte** [wasabeef/awesome-android-ui#70]
Can you add this:

https://github.com/michelelacorte/ElasticProgressBar

please?

Thank you.

**Comment by JackLauu** [comment]
It's seems good, how to add?

**Comment by Gumarelo** [comment]
What are the difference with this repository? https://github.com/Tibolte/ElasticDownload

**Comment by michelelacorte** [comment]
More methods, ease of implementation, compatibility higher! @Gumarelo

**Comment by Gumarelo** [comment]
Great @michelelacorte

**Comment by michelelacorte** [comment]
Thanks!! @Gumarelo
