### ISSUE TITLE
Add Like Button / Twitter Heart Animation

### ISSUE THREAD

**Issue by jd-alexander** [wasabeef/awesome-android-ui#81]
It would be nice if this library was added. it mimics the Twitter heart animation that's used for liking https://github.com/jd-alexander/LikeButton

**Comment by EgyptianM** [comment]
Wow awesome
just what I was searching for :+1:

**Comment by jd-alexander** [comment]
Awesome glad you like it!

**Comment by Ram8948** [comment]
can i add it to simple button?

**Comment by jd-alexander** [comment]
Not sure. Never tried it.
