### ISSUE TITLE
Offtopic

### ISSUE THREAD

**Issue by ErickDaniel** [wasabeef/awesome-android-ui#99]
Hi i'm trying to create modules in Android but i'm newbie do you have some tutorials to create it?
i'm trying to create personal textviews but it doesn't work :cry:

**Comment by JackLauu** [comment]
@ErickDaniel May be you could have a reference by http://developer.android.com/training/index.html

**Comment by danielgomezrico** [comment]
@ErickDaniel Also https://www.udacity.com/google
